version: "3"

services:
  postgres:
    image: postgres:14
    container_name: postgres14
    ports:
      - "5050:5432"
    volumes:
      - ./.docker/postgres/data_persist:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ecomm@admin
      POSTGRES_DB: ecommDB
